### ISSUE TITLE
Jetpack: Add tests for critical Jetpack Connect flows

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-e2e-tests#1000]
In addition to tests for the specific flows in https://github.com/Automattic/wp-e2e-tests/issues/777, we should make sure the critical Jetpack Connect flows are covered. We currently have tests for:

* Connecting a site with the free plan from Calypso (Jetpack installed)
* Connecting a site with the free plan from Calypso (Jetpack not installed)
* Connecting a site with the free plan from WP Admin

Jetpack Connect flows to consider (internal ref: PCYsg-dek-p2):

1. Plan selector shown upfront: `jetpack/connect/store/[monthly]`
2. Automatically adds a yearly plan to the cart: `jetpack/connect/personal|premium|pro`
3. Automatically adds a monthly plan to the cart: `jetpack/connect/personal|premium|pro/monthly`
4. "Install Jetpack" prompt shown upfront: `jetpack/connect/install`
5. Non-English flow, e.g. Spanish: `jetpack/connect/es` & `jetpack/connect/install/es`
6. Automatically submits the site URL: `jetpack/connect/?url=https://yourgroovydomain.com` (covered by existing tests) or variants of other flows with Site URL added e.g. `jetpack/connect/pro/?url=https://yourgroovydomain.com` 

We should also consider how users enter these flows, e.g. from Jetpack.com:

*  "Try it free" button at https://jetpack.com/
 * Paid plan at https://jetpack.com/pricing/
 * "Install Jetpack" button on feature pages like https://jetpack.com/features/design/
* How else?

**Comment by rachelmcr** [comment]
I would prioritize automating these flows:

* Jetpack.com "Try it free" button (hits `jetpack/connect/store` flow)
* Jetpack.com Pricing page, selecting a paid plan e.g. Premium (hits `jetpack/connect/install` or `jetpack/connect/premium` depending on wp.com logged-in status, so I'd do those two variants)

I'm not sure what flows exist currently that send users through flow 3 (adding a monthly plan) but that'd probably be next on my list. What do you think, @alisterscott? How many of these flows do you think we should automate tests for?

**Comment by alisterscott** [comment]
Thanks for organizing this @rachelmcr 

> What do you think, @alisterscott? How many of these flows do you think we should automate tests for?

The ones you mentioned are good initial candidates.

> "Install Jetpack" button on feature pages like https://jetpack.com/features/design/

I'm trying to work out whether this is actually any different than just via the pricing page, it doesn't appear to be, so I think we could not worry about these specific ones that have different origins but same entry points - what do you think?

**Comment by rachelmcr** [comment]
>I'm trying to work out whether this is actually any different than just via the pricing page, it doesn't appear to be, so I think we could not worry about these specific ones that have different origins but same entry points - what do you think?

Agreed. I'm just double checking with the Jetpack team to make sure the logged-out pricing page behavior is expected, since the `jetpack/connect/install` flow doesn't preselect the plan. (Internal ref: p7kMJG-4qe-p2)

I'll get started on the first flow (from the "Try it free" button) for now.

**Comment by rachelmcr** [comment]
The logged-out behavior on the pricing page was unintentional and is fixed now, so let's start with these flows:

* Jetpack.com "Try it free" button (hits `jetpack/connect/store` flow)
* Jetpack.com Pricing page, selecting a paid plan e.g. Premium (hits `jetpack/connect/premium` flow)
* Jetpack.com "Install Jetpack" button (hit `jetpack/connect/install` flow)

**Comment by brbrr** [comment]
> Jetpack.com "Try it free" button (hits jetpack/connect/store flow)
is implemented here https://github.com/Automattic/wp-e2e-tests/pull/1007

**Comment by brbrr** [comment]
I'm going to start "Install Jetpack" flow while logged out

**Comment by alisterscott** [comment]
I'm going to close this placeholder and if there are any missing specific flows we can create individual items to work on
