### ISSUE TITLE
Update Mailosaur to 5.0.2

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-e2e-tests#1017]
There is a new major version had released: https://github.com/mailosaur/mailosaur-node

The API has changed, so complete re-write of `EmailClient` would be required. 

Benefits are unknown 🙃

**Comment by alisterscott** [comment]
@abidhahmed [points out](https://github.com/Automattic/wp-e2e-tests/pull/1203#pullrequestreview-119796574) we get:

> https://mailosaur.com/docs/api/#operation/Messages_WaitFor

for free in upgrading to this
