### ISSUE TITLE
Simple Payments: add a purchase test

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-e2e-tests#1030]
Add a test to verify that payments may go through on a few core cases for existing products:
- USD with a decimal value eg `1.99`
- USD with whole units `20`
- Spot checks with other currencies like JPY

We may need to consult the Flow team on how best to structure this.

Related:
https://github.com/Automattic/wp-calypso/issues/22939
D10823-code
p58i-6nm-p2 for manual test instructions

cc @Automattic/lannister @retrofox

**Comment by alisterscott** [comment]
Being addressed in #1204
