### ISSUE TITLE
Simple Payments: add a test to create a product

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-e2e-tests#1031]
Let's add a test that looks at the happy path for creating a simple payment product. 

- Create a new post or page
- Add a simple payment in USD
- Verify that we can publish the post

#### Related
Automattic/wp-calypso#22939
D10823-code
p58i-6nm-p2 for manual test instructions

cc @Automattic/lannister @retrofox

**Comment by alisterscott** [comment]
Hi @gwwar 

We already have this, I added it when we launched payment buttons:

https://github.com/Automattic/wp-e2e-tests/blob/master/specs/wp-post-editor-spec.js#L975

We don't actually buy anything with the button - this will be more complicated

**Comment by gwwar** [comment]
Got it, let's close this one! 

But I think we should figure out some sort of integration test (depending on needs it doesn't necessarily need to be done in browser) to verify that the paypal link is still working. Even if the breakage is not on our side, it'd be good to get some monitoring up.

**Comment by alisterscott** [comment]
The decimal issue meant the paypal dialog didn't even show, so similar issues could be found with an e2e test that clicks the payment button and waits for the paypal dialog, might be something worth adding - quite simple
