### ISSUE TITLE
Jetpack Tests: Test failures due to "Completing connection" timeouts

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-e2e-tests#1070]
Some Jetpack Connect tests are failing when the connection authorization (the "Completing connection" screen) takes too long. We could increase the timeout wait for this step to give the connection longer to complete.

Test failure:

> TimeoutError: Timed out waiting for element with css selector of '.plans-features-main__group' to be present and displayed

Screenshot:

![failed-en-desktop-can-click-the-free-plan-button-1521703231465](https://user-images.githubusercontent.com/8658164/37775461-f0619c38-2dda-11e8-9656-f16503811591.png)

Test run: https://circleci.com/gh/Automattic/wp-e2e-tests-jetpack/3421

**Comment by bsessions85** [comment]
In some other tests I'm working on, that are related to this, I tried waiting until the spinner goes away. It seems to work.
