### ISSUE TITLE
Tests for branches: Disable slack notifications

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-e2e-tests#1071]
`wp-e2e-tests-for-branches` are runnng against varoius PRs for `wp-calypso` and `jetpack`. Now these tests are reporting into #e2e-full-suite-notif slack channel, which is creating not needed noise.

We should disable channel notifications, and if possible - send direct pings to PR creator with a nice message explaining what to do next (how to run locally, where find help, etc)

**Comment by alisterscott** [comment]
@brbrr I believe you've done this already?

**Comment by brbrr** [comment]
Yes, Its already done. Thanks for keeping our issues up to date!
