### ISSUE TITLE
Add unique locators for Onboarding pages

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-e2e-tests#1196]
Right now Onboarding pages are using `driver.sleep` to wait for page loads. This approach isn't ideal, and we should add some unique locators into pages (in Calypso) so we can get rid of these `sleep` calls.

`driver.sleep` added here: https://github.com/Automattic/wp-e2e-tests/pull/1187

**Comment by alisterscott** [comment]
One thing I noticed is that every Jetpack On Boarding page is that the expected element is the same:

`super( driver, By.css( '.jetpack-onboarding' ) );`

so it'll never wait for a new page to load.

The idea behind the expected element is to wait for a new page with the new element so we know we're exactly where we're meant to be - it may be possible to add some unique elements to each Jetpack OB page which may remove the need to have hard coded waits - just an idea
