### ISSUE TITLE
Fix TypeError: Cannot read property 'then' of undefined' in Signup spec

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-e2e-tests#1212]
There is a TypeError in `after` hook in "Sign up for a domain only purchase coming in from wordpress.com/domains in EUR currency" test (https://github.com/Automattic/wp-e2e-tests/blob/master/specs/wp-signup-spec.js#L603)

It looks like it comes from async / await changes, and exactly from `SidebarComponent#selectSettings` method, which isn't  return `thanble` for success.

**Comment by alisterscott** [comment]
@Stojdza would you mind taking a look at this?

**Comment by Stojdza** [comment]
This should be fine now.
