### ISSUE TITLE
Error when emails is undefined

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#1213]
Occasional error in CircleCI:

`Cannot read property 'html' of undefined`

example: https://circleci.com/gh/Automattic/wp-e2e-tests/19873#tests/containers/1

**Comment by alisterscott** [comment]
@Stojdza I saw this recently, would it be something to do with promises in the email client? Any ideas about how we'd fix this, or workaround it?

**Comment by alisterscott** [comment]
Another here: https://circleci.com/gh/Automattic/wp-e2e-tests/19905#tests/containers/1

**Comment by brbrr** [comment]
I think I know the reason. The issue comes from `#pollEmailsByRecipient` and its validator. The current validator allows exiting polling on the first try. Replacing validator with something like this: `emails => emails.length > 0` should potentially fix this issue.

**Comment by alisterscott** [comment]
This should be fixed by https://github.com/Automattic/wp-e2e-tests/pull/1223

**Comment by Stojdza** [comment]
Thanks @abidhahmed!
