### ISSUE TITLE
Create a cron job to clean-up scheduled posts

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-e2e-tests#1229]
Our `defaultUser` has a warning in its Report Card: `This blog has had post scheduling limited due to having 401 scheduled posts.`

We need to review tests accounts used in `Schedule Basic Public Post` test and create/update a CRON job to clean-up these scheduled posts/

**Comment by Stojdza** [comment]
@brbrr @alisterscott What do you think about cleaning after test execute successfully?
It looks to me as a long-term solution, but it will extend execution for some time.

**Comment by alisterscott** [comment]
Sounds like a plan @Stojdza 

I think it woudn't add that much time to simply trash the scheduled post - we could revisit using the wpcom API to do this directly without calypso - @tammullen did some API work in his trial

**Comment by brbrr** [comment]
I would prefer a cron job since it is a simple and bullet-proof solution. From another hand - removing it may a nice way to test removal functionality. 

[IMO] Ideally - all the cleanup should be done from within testing code as an `after` block, so using WP API is a way to go. [/IMO]

**Comment by Stojdza** [comment]
I agree, it would be nice to cover _trash scheduled post_ functionality.

If there is a need for trashing on more than one place we should consider using API for all except one.

**Comment by alisterscott** [comment]
> If there is a need for trashing on more than one place we should consider using API for all except one.

Sounds like a good approach
