### ISSUE TITLE
Separate WPCOM and WPADMIN login pages

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-e2e-tests#1252]
`LoginPage#login` is designed to work on both WPCOM and WPADMIN login pages, which is conceptually not correct. we need to separate these 2 pages completely (and maybe use some common parent page)

**Comment by alisterscott** [comment]
It looks like we already have a `WPAdminLogonPage` which extends the other - although this needs some clean up and the base page selectors still need to be cleaned up also

**Comment by alisterscott** [comment]
I am addressing this in #1258 

The wp-admin doesn't extend the calypso one - they both just extend the new async base container now :)

**Comment by alisterscott** [comment]
This was fixed by #1258
