### ISSUE TITLE
wp-theme-switch-spec.js is failing with disabled promise manager

### ISSUE THREAD

**Issue by Stojdza** [Automattic/wp-e2e-tests#1292]
After we've switched to Async Base Container, wp-theme-switch-spec.js started to fail when promise manager is disabled: https://circleci.com/gh/Automattic/wp-e2e-tests/20784#tests/containers/1

**Comment by alisterscott** [comment]
Weird, this was problematic:

```
let customizerPage = await CustomizerPage.Expect( driver );
let displayed = await customizerPage.displayed();
return assert( displayed, 'The customizer page was not displayed' );
```

but this works and achieves the same thing:

`return await CustomizerPage.Expect( driver );`

maybe something to do with the iFrame but not worth spending time investigating IMO

**Comment by alisterscott** [comment]
I think I know why, this spec is using Chai for assertions and so it isn't behaving the same as other assertions. When we do #1274 this should be fixed
