### ISSUE TITLE
Temporarily disabled ensureSaved() call before Preview

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#131]
To work around https://github.com/Automattic/wp-calypso/issues/6612, I commented out the line in the Page/Post editor specs to `ensureSaved()` before launching the Preview.  It shouldn't be necessary, since Preview forces a save anyway, but I'd like to re-enable that step once the wp-calypso bug is fixed so we can verify that it's working again.  This issue is being written to track it so we don't forget.

https://github.com/Automattic/wp-e2e-tests/blob/fix/remove-personal-plan-from-tests/specs/wp-page-editor-spec.js#L73
https://github.com/Automattic/wp-e2e-tests/blob/fix/remove-personal-plan-from-tests/specs/wp-post-editor-spec.js#L141

**Comment by alisterscott** [comment]
This issue has been addressed and the specs now call `ensureSaved()` so closing this issue.
