### ISSUE TITLE
Upgrade to node 10.5.0 to match wp-calypso

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#1316]
branch: upgrade/node-10.5.0
PR title: Update Node to 10.5.0

- [x] this main repo
- [x] https://github.com/Automattic/wp-e2e-tests-for-branches
- [x] https://github.com/Automattic/wp-e2e-tests-canary
- [x] https://github.com/Automattic/wp-e2e-tests-woocommerce
- [x] https://github.com/Automattic/wp-e2e-tests-i18n
- [x] https://github.com/Automattic/wp-e2e-tests-ie11
- [x] https://github.com/Automattic/wp-e2e-tests-jetpack
- [x] https://github.com/Automattic/wp-e2e-tests-jetpack-be

**Comment by alisterscott** [comment]
The Jetpack ones I will let the Jetpack crew test these

**Comment by brbrr** [comment]
Jetpack-related PRs approved and merged. Thanks for keeping it in sync!
