### ISSUE TITLE
Transfer domain test fails as page continues to load

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#1382]
I've disabled this test as it's causing our builds to fail

This is the screenshot from CircleCI: 
![failed-en-desktop-can-see-the-transfer-precheck-page-1533100053817](https://user-images.githubusercontent.com/128826/43502348-a7fc1574-959d-11e8-8214-ace9b684ce8a.png)

@bsessions85  updated the timeout to double (40 secs) but this didn't seem to help

@aidvu as the author of this test - any ideas what's going on here? 40 seconds seems like ample time to wait for the screen to appear - is there anything we can do to re-enable this test and get it to pass consistently?

**Comment by aidvu** [comment]
I tested now both locally and wp.com and it works. Maybe related to the outage yesterday?
