### ISSUE TITLE
Not deleting free .blog test sites.

### ISSUE THREAD

**Issue by delputnam** [Automattic/wp-e2e-tests#1397]
It looks like when we are never deleting the test sites that are created here:

https://github.com/Automattic/wp-e2e-tests/blob/master/specs/wp-signup-spec.js#L1746

Since .blog subdomains all have mapping records, not deleting these sites leaves lots of records for test sites in the table. There is a job that will clean up the mapping records for sites with deleted .blog subdomains and remove them from the table.

Would it be possible to start deleting these test sites?

**Comment by bsessions85** [comment]
yes, I'll get this added today

**Comment by Stojdza** [comment]
@delputnam We can delete the site at the end of every successful test execution. Does that sound ok?

**Comment by delputnam** [comment]
Yep. That should work. Thank you!

**Comment by Stojdza** [comment]
@delputnam Done! (Just needs to pass the review :) )
