### ISSUE TITLE
Remove Visual-Diff Tests from Codebase

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-e2e-tests#1424]
To do:
- [x] Remove screenshot steps from test specs
- [x] Remove eyes helper
- [x] Remove from run.sh and magellan
- [x] Remove from config
- [x] Remove related documentation
- [x] Update [Calypso A/B test docs](https://github.com/Automattic/wp-calypso/blob/master/client/lib/abtest/README.md#updating-our-end-to-end-tests-to-avoid-inconsistencies-with-ab-tests)
- [x] Remove [visdiff wrapper repo](https://github.com/Automattic/wp-e2e-tests-visdiff)

**Comment by alisterscott** [comment]
Thanks for completing this 🙏
