### ISSUE TITLE
Use themes pseudo-select dropdown instead of editing URL

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#152]
Right now the themes list is filtered by directly editing and reloading the URL (https://github.com/Automattic/wp-e2e-tests/commit/9fd5292a602bb065a85fbbe856b73ec576049f6d), because the select dropdown has been unreliable at the speed the tests run.  The filter slug was updated in https://github.com/Automattic/wp-calypso/pull/6886, which broke the tests, but did not break the actual user experience.  I've fixed the tests in #151.

This issue is to track the fact that using the URL directly is just a workaround, and at some point we should go back and get the dropdown working correctly (either by handling it in our tests,  or driving a fix to wp-calypso).

cc: @alisterscott

**Comment by alisterscott** [comment]
Thanks for raising this as an issue 👍

**Comment by hoverduck** [comment]
We should be able to remove this once "Magic Search" is turned on in production

https://github.com/Automattic/wp-calypso/milestones/Themes:%20Showcase%20M5-MagicSearch

**Comment by alisterscott** [comment]
Fixed by #528
