### ISSUE TITLE
Run various builds against an e2e PR

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#1556]
When creating an e2e PR we should use CircleCI workflows to run a variety of builds

1. IE11 canaries still work
2. Safari 10 canaries still work
3. WooCommerce still works
4. Full tests still work
5. Jetpack is fine

We could get rid of the logic to look at branch name and just run the lot

**Comment by brbrr** [comment]
That's a great idea! Please keep in mind that running Jetpack tests too often (e.g. on every commit) might overload Jurassic.ninja.
