### ISSUE TITLE
Update selectors for plan purchase in signup

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#163]
#162 added a lot of really funky xpath selectors to accommodate the new plans features layout, since none of the elements (specifically the selection buttons) have identifiers linking them to the plan you're selecting -- https://github.com/Automattic/wp-calypso/issues/7092

When that issue is fixed we'll need to redo the selectors again.

**Comment by rachelmcr** [comment]
It looks like these selectors were updated in #165. Closing as resolved.
