### ISSUE TITLE
Update Gutenberg contact from test to use contact form block

### ISSUE THREAD

**Issue by JavonDavis** [Automattic/wp-e2e-tests#1640]
Currently, the Gutenberg contact form test from https://github.com/Automattic/wp-e2e-tests/pull/1639 uses a shortcode to insert the contact form block. Once the native contact form block is live we should use that or at the very least add to the existing test.

**Comment by JavonDavis** [comment]
Nice! Thanks @simison! 

@gwwar any idea when this will be available from Gutenberg in WPCOM? 

I did test this out on a site with Gutenberg and Jetpack enabled and the form wasn't showing in the preview and publish.. I've attached screenshots and a recording link below. Ignoring the last part of the recording where it navigates back to the wp-admin vs wpcalypso environment was there more information I needed to enter to see it in the Preview and Publish? 


<img width="1678" alt="screen shot 2018-11-22 at 11 08 44 am" src="https://user-images.githubusercontent.com/6520461/48913838-9e41c800-ee47-11e8-951b-0856df40daba.png">
<img width="1680" alt="screen shot 2018-11-22 at 11 09 24 am" src="https://user-images.githubusercontent.com/6520461/48913844-a13cb880-ee47-11e8-9d5c-6e2a69a40780.png">
<img width="1679" alt="screen shot 2018-11-22 at 11 09 42 am" src="https://user-images.githubusercontent.com/6520461/48913847-a39f1280-ee47-11e8-96fa-8ac888f792bd.png">
<img width="1679" alt="screen shot 2018-11-22 at 11 10 11 am" src="https://user-images.githubusercontent.com/6520461/48913849-a6016c80-ee47-11e8-8d56-4b69eb3f7975.png">

Recording link: https://www.dropbox.com/s/6rtk1ipfmy5mr0x/contact-form.mov?dl=0

**Comment by gwwar** [comment]
@lezama or @johnHackworth would be able to better answer that for block timelines.

**Comment by lezama** [comment]
We are aiming for early next week  👍

**Comment by JavonDavis** [comment]
Closed in https://github.com/Automattic/wp-e2e-tests/pull/1695
