### ISSUE TITLE
Tests execution status update

### ISSUE THREAD

**Issue by Stojdza** [Automattic/wp-e2e-tests#1668]
In several wp-calypso and wp-e2e-tests PRs test execution status wasn't updated after execution is finished - status is still running. 

Example: https://github.com/Automattic/wp-calypso/pull/28907 
<img width="679" alt="screen shot 2018-11-28 at 16 29 43" src="https://user-images.githubusercontent.com/7116222/49162301-e3c03280-f32a-11e8-962d-2ef8652352d5.png">
<img width="671" alt="screen shot 2018-11-28 at 16 29 55" src="https://user-images.githubusercontent.com/7116222/49162304-e6228c80-f32a-11e8-97bd-7474347db26b.png">

Other PRs:
https://github.com/Automattic/wp-e2e-tests/pull/1666
https://github.com/Automattic/wp-calypso/pull/28907
https://github.com/Automattic/wp-e2e-tests/pull/1667

**Comment by sirreal** [comment]
Seems to be happening more and more:

https://github.com/Automattic/wp-calypso/pull/28920
- https://circleci.com/gh/Automattic/wp-desktop/28009
- https://circleci.com/gh/Automattic/wp-e2e-canary-for-branches/13593
- https://circleci.com/gh/Automattic/wp-e2e-canary-for-branches/13594
- https://circleci.com/gh/Automattic/wp-e2e-canary-for-branches/13595

**Comment by sirreal** [comment]
I suspect something is up with CircleCI notify or the endpoint handling the notification:

https://github.com/Automattic/wp-desktop/blob/3bf7cabd0292fe79d4e183e932eb56136eaf746d/.circleci/config.yml#L379-L381
https://github.com/Automattic/wp-e2e-tests-for-branches/blob/00efd7fc00c87e42bb688e10036a0278dd44b6fa/.circleci/config.yml#L38-L40

**Comment by bsessions85** [comment]
I think this was an issue with CircleCI. In my testing it wasn't hitting the webhook after the build completed. It suddenly started working again shortly before CircleCI started having bigger issues.  Now I see it hitting occasionally but not for every build, so I will check it again tomorrow and hopefully CircleCI will settle down some.
