### ISSUE TITLE
Fix: Better detect failures for cross-browser tests

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#189]
With the cross-browser tests being run in parallel via grunt, the return codes for the `run.sh` script is always set to 0, so a failure in one browser doesn't cause all the others to stop/skip.  But that also means that CircleCI is always marking the tests as passing, and the only indication of failure is in the Slack pings or SauceLabs UI.

This works for now — but in the future we should investigate how to make the parallel tests cancel each other when one fails. Needs further investigation.

**Comment by hoverduck** [comment]
Worth revisiting if/when we move away from CircleCI to a self-hosted Docker-based system

**Comment by alisterscott** [comment]
@hoverduck is this still an issue that needs work?

**Comment by hoverduck** [comment]
I'll go ahead and close it.  I don't think it will be an issue anymore after @rachelmcr finishes the visdiff redesign.
