### ISSUE TITLE
Can't run the tests properly

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-e2e-tests#194]
As discussed in https://github.com/Automattic/wp-calypso/pull/7129, I'm trying to run the e2e tests locally. Unfortunately, I'm running into several issues. Maybe I'm doing something wrong. Here are the issues:

1. Installation guide should list JRE and JDK as dependencies;
1. It should also say to run your local Calypso instance if you plan to test on it;
2. After running `NODE_ENV=lamosty ./run.sh -g`, I get an error about missing properties in the local config file. The property in question is `testSiteForNotifications` which is not listed in the "Config Values" list in the main README file. I had to put a random string with that property to my local config to get it running;
3. After starting the test suite, it opens Chrome window and goes to `https://wordpress.com/wp-login.php?redirect_to=http://calypso.localhost:3000`, trying to log in. After filling in the details and clicking on "Log in", it's redirected to https://wordpress.com/wp-login.php which is a blank page:

![selection_019](https://cloud.githubusercontent.com/assets/4988512/17554451/24c836f8-5f0b-11e6-9e14-6e5dc19f9b7e.jpg)

The test then fails with "Can log in" failed. Sometimes it's successfully redirected to local Calypso instance.

cc @hoverduck @gwwar

**Comment by hoverduck** [comment]
Thanks for the feedback.  I'll update our README and config/local.example.json file with the missing information.

I'm not sure what's going on with the login redirect for you, though...I don't think I've ever seen it fail that way.  After the test is done and leaves you on the blank page, can you open the dev tools and see if there's anything in the console?

I'm also working on getting a full test run against https://github.com/Automattic/wp-calypso/pull/7129 so you can merge your code in and don't need to get hung up on this.

**Comment by lamosty** [comment]
> I'll update our README and config/local.example.json file with the missing information.

Thanks. Another question: do I need to be proxied and/or logged into WP.com when running the tests?

> After the test is done and leaves you on the blank page, can you open the dev tools and see if there's anything in the console?

Will try that and let you know.

> I'm also working on getting a full test run against Automattic/wp-calypso#7129 so you can merge your code in and don't need to get hung up on this.

Thanks, that'll be great!

**Comment by lamosty** [comment]
> After the test is done and leaves you on the blank page, can you open the dev tools and see if there's anything in the console?

Nothing in Console. This is how Request and Response headers look like:

![selection_022](https://cloud.githubusercontent.com/assets/4988512/17557724/981440d6-5f18-11e6-8dd3-45ae6084a44d.jpg)

Maybe I have wrong user/pass in the testing conf? I would I get a correct/new one?

**Comment by hoverduck** [comment]
> Another question: do I need to be proxied and/or logged into WP.com when running the tests?

No, the tests should log themselves in with the account information in the `config/local-*.json` file.  That's the whole reason we hit https://wordpress.com first and then redirect to the destination (in this case calypso.localhost:3000).  And in the `config/default.json` file there's the `"proxy": "direct"` option, which bypasses any local proxy configuration.  You can override that to "system" if you do want to use the proxy

**Comment by lamosty** [comment]
I see, thanks.

After using the new config file, I no longer get the blank pages! Close this issue on will. :)

**Comment by hoverduck** [comment]
Updated README and config/local.example.json with #196
