### ISSUE TITLE
Create new test for clicking site content link mobile sidebar

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#243]
Create coverage for this bug: https://github.com/Automattic/wp-calypso/issues/1881

**Comment by hoverduck** [comment]
This should also cover Jetpack sites.

Also ref this [recent failure](https://github.com/Automattic/wp-calypso/pull/11244)

**Comment by chenchaoyi** [comment]
Tests added as in specs/wp-view-site-spec.js
