### ISSUE TITLE
Workaround sleep statement added for page/post preview

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#273]
With the changes introduced in https://github.com/Automattic/wp-calypso/pull/8292 the page/post preview specs were failing and I'm not entirely sure why.  As soon as the preview pane was loaded the tests would fail, even though they should be blocking `until.ableToSwitchToFrame( iFrameSelector )`.  My only guess is that the frame is loading briefly and satisfying that condition, but then disappearing and reloading?

Adding a 1s sleep (#272) is enough to bypass the issue, but that's obviously not the ideal solution.  I don't have time to dig into it further at the moment, so I'm going to leave that sleep in and we can pull it back out later.

@alisterscott you did all the work to set up these iframe tests, any ideas?

**Comment by alisterscott** [comment]
It seems weird that switching to the iFrame no longer works.

I found there's an element which indicates that the preview is loading, so I added a wait for this element before attempting the switch which means we don't have to explicitly sleep - I tested it and it works well so I've merged it in #276
