### ISSUE TITLE
Remove duplication across editor sidebar and editor page

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#282]
These page have a few methods with the same functionality which is duplicated. It would be good to remove this duplication, possibly by combining into a single page object that switches between the sidebar and the editor, or an editor page that includes a sidebar (composition)

**Comment by hoverduck** [comment]
If we don't get time to fix this proactively, this should be done if/when the affected code is being updated for other reasons.

**Comment by hoverduck** [comment]
This may be a good opportunity to consolidate this code - https://github.com/Automattic/wp-calypso/pull/11536

**Comment by alisterscott** [comment]
Being addressed in #476

**Comment by alisterscott** [comment]
Fixed in #476
