### ISSUE TITLE
Measure performance of interactions

### ISSUE THREAD

**Issue by ehg** [Automattic/wp-e2e-tests#292]
Whilst we were discussing performance related matters in Calypso, it came up that the e2e tests could provide us with a way of measuring user interaction timings, e.g. how long does it take between clicking a sidebar menu item, and for the section to be rendered.

I was wondering whether this would be feasible, given:
- Mocha already gives us timing data, although we'd probably want to be able to define what's reported as slow.
- The e2e tests already test a lot of interactions, perhaps giving some this timing data to us for free.
- We could write performance specific tests, to control our variables a bit more.

On the other hand, full e2e tests are highly dependant on network/container conditions, so the timings may differ too much to be of use.

@alisterscott @hoverduck — what do you think? Is this feasible/useful/sensible? :)

**Comment by ehg** [comment]
Also looping @gwwar in, as I think you suggested it.

**Comment by hoverduck** [comment]
Yeah, definitely feasible/useful/sensible/all of the above.  It's easy enough to add a before/after clause to any or all tests to record timing.  A couple options come to mind for implementation...either using the before/afterEach sections to record start/stop times, or possibly integrate it into the custom reporter we're using.  Not sure if either way makes more sense, I'd have to try it out and see.

The tougher part is managing that data...where do we record it, how do we retrieve it, etc?

**Comment by ehg** [comment]
> or possibly integrate it into the custom reporter we're using

I wonder if this would give us more flexibility. Especially if/when we look at 'tagging' certain blocks, we could tag actions we want to measure with `#measured` or something.

> The tougher part is managing that data...where do we record it, how do we retrieve it, etc?

I think we could use our existing infrastructure for this — we have the ability to measure timing like things via a few different methods and, and we can display them in Grafana.

**Comment by hoverduck** [comment]
> I think we could use our existing infrastructure for this

Is there a Field Guide page or anything about how to use that?  FYI, I copied this to a P2 for sharing internal a8c resources - p6fDka-bi-p2

**Comment by hoverduck** [comment]
Closing this in favor of the P2 post linked above
