### ISSUE TITLE
Visdiffs: Combine components into fewer screenshots

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#309]
The way I initially built the visdiff tests was to screenshot a single devdocs page with all of the components, but that caused problems with the screenshot being too large to be handled by Applitools, as well as issues with a couple components with dynamic heights causing everything below them on the page to miscompare.  But now we're running 900 comparisons per test, and going over our paid allocation.

This issue is to find a way to more intelligently group them to avoid those problems.  Off the top of my head I think they'd need to be aligned horizontally instead of vertically, maybe in groups of 3-5?  Not sure whether it would make more sense to build something to dynamically rearrange the components from inside the test, or build a new view into Calypso.

**Comment by lancewillett** [comment]
This is a good direction: finding the balance between Applitools runs and having too big a screenshot to compare.

I think the alternate Calypso view would be a nice way to solve it.

**Comment by alisterscott** [comment]
> I think the alternate Calypso view would be a nice way to solve it.

👍

**Comment by hoverduck** [comment]
This is still a good idea, but not something we're going to worry about right now.  If/when we add more visual diff tests we can revisit this idea.
