### ISSUE TITLE
Workaround for theme selection bug

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#321]
This issue tracks the workaround for https://github.com/Automattic/wp-calypso/issues/9298 to reload the page before selecting a theme.

**Comment by alisterscott** [comment]
Should we add a slack warning for this so we know there's a workaround in place?

**Comment by hoverduck** [comment]
Good idea...right now I'm keeping a pretty close eye on it waiting for the fix, but if it drags out I could easily lose track.  #324

**Comment by alisterscott** [comment]
This should be closed soon by #402 as soon as it is merged
