### ISSUE TITLE
Should be aware of control flow deprecation

### ISSUE THREAD

**Issue by manoj9788** [Automattic/wp-e2e-tests#329]
Just raising this, work on changing parts where control flow is used.  If you guys are already aware and have plans to  change we can close this.
https://github.com/SeleniumHQ/selenium/issues/2969

**Comment by hoverduck** [comment]
Thanks @manoj9788....Selenium 3.0.0 is on my radar, but I hadn't actually spent much time looking at the new async stuff yet.  We'll leave this issue open to make sure it's on our minds as we move forward.

cc: @alisterscott

**Comment by manoj9788** [comment]
@hoverduck Sure, am happy to help. I will soon put a new repository on this showcasing a demo.

**Comment by alisterscott** [comment]
We probably need to prioritize this now that we're on Node 8.9.x

**Comment by alisterscott** [comment]
We should move to using async/wait: https://github.com/SeleniumHQ/selenium/wiki/WebDriverJs
