### ISSUE TITLE
Create separate account for visdiff tests

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#342]
The visdiffs run using the same account as the main e2e tests, which means the contents of a few of the /devdocs/design components are slightly more dynamic than I'd like.  It hasn't been much of an issue in the past, and I like having an account with a large amount of "real" data on it, but I just noticed that when the current account was cleared out for the first time yesterday it led to this difference:

![screen shot 2016-12-14 at 10 54 37 am](https://cloud.githubusercontent.com/assets/7233112/21189175/d18c8266-c1eb-11e6-8e25-8d1dbd34bf60.png)

This makes me think it's worth just setting up that separate account so I know that it'll always have posts of those different types to make sure we're validating the right output.

**Comment by lancewillett** [comment]
That makes sense to me.

**Comment by alisterscott** [comment]
Sounds like a good idea, since we it's unlikely we'll see the logon issues with the vis-diff account we see on the e2e accounts.

**Comment by lancewillett** [comment]
> since we it's unlikely we'll see the logon issues with the vis-diff account we see on the e2e accounts

Noting the login delay issue is addressed now.

**Comment by alisterscott** [comment]
We already have a visdiff account but we aren't using it. This would be making sure the account is usable and switching over to it.
