### ISSUE TITLE
Add dynamic step numbering to signup spec

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#356]
PR #285 added dynamic step numbering to the signup spec, so steps could be added/removed/moved without having to edit every step number further down the line.  But I forgot to merge it, and now it's not worth the hassle to rebase that branch and add the feature back in.  So this issue tracks it as an enhancement, and I'll add the feature back the next time I'm working on the signup spec.

**Comment by alisterscott** [comment]
This would be a nice to have.

**Comment by bsessions85** [comment]
Added in PR #671
