### ISSUE TITLE
Shutdown: use actual "Log Out" action in /me to log out

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-e2e-tests#366]
For e2e tests, we should add a clearing step to log out the current user as part the test teardown steps, that way there are fewer user sessions to manually clean up later. (User sessions build up over time if user isn't logged out correctly.)

What are your thoughts for handling it gracefully?

Answered by @hoverduck 

> @alisterscott what do you think about updating the ensureNotLoggedIn function to navigate to /me and click Sign Out before clearing cookies/localStorage. I think we still want to clear those out to make sure everything is clean, but at least this would also clean up the sessions, and would be the logical place to put that step.

**Comment by rich211** [comment]
Sorry guys my bad just learning sorry for messing things up


This<https://itunes.apple.com/app/apple-store/id922793622?pt=814382&mt=8&ct=how_i_email> is how I Email now


On Jan 18, 2017 at 10:52 AM, <Lance Willett<mailto:notifications@github.com>> wrote:


For e2e tests, we should add a clearing step to log out the current user as part the test teardown steps, that way there are fewer user sessions to manually clean up later. (User sessions build up over time if user isn't logged out correctly.)

What are your thoughts for handling it gracefully?

Answered by @hoverduck<https://github.com/hoverduck>

@alisterscott<https://github.com/alisterscott> what do you think about updating the ensureNotLoggedIn function to navigate to /me and click Sign Out before clearing cookies/localStorage. I think we still want to clear those out to make sure everything is clean, but at least this would also clean up the sessions, and would be the logical place to put that step.

**Comment by alisterscott** [comment]
Our log in tests use the log out button so we cover that scenario. Closing for now.

**Comment by lancewillett** [comment]
Notes from Scott Stancil:

> On one hand it’s more realistic testing that might find bugs if the user isn’t logged out cleanly. But on the other hand, the bugs that are revealed that way are likely to be incredibly difficult to recognize. The tests would (potentially) only fail when run in a certain order, with seemingly random results.

> I think it’s more important to take a deterministic approach with each test and be able to execute them knowing for a fact that they have the same setup and starting point every time.

For the e2e testing accounts we can just clear the sessions manually every so often (as an admin user from the WordPress.com dashboard).
