### ISSUE TITLE
Investigate the mocha retry option

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#37]
Mocha has a command line option to automatically retry failing tests.  I haven't really looked at it yet, but offhand I don't think it will work for the way we've structured our tests, since they're not all completely independent.  But I'm curious if I could dynamically set the retry flag for just certain tests (like login).

**Comment by alisterscott** [comment]
I've been trying retries without failure in known places which seems to be working fairly well.

**Comment by hoverduck** [comment]
Yeah, it's been working great.  I'll go ahead and close this out.
