### ISSUE TITLE
Workaround: Debug flag added to visdiffs

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#380]
https://github.com/Automattic/wp-e2e-tests/pull/379 added a `?debug=true` flag to all wpcalypso page loads to prevent minimization.  This will need to remain in place until https://github.com/Automattic/wp-calypso/issues/11079 is fixed

**Comment by alisterscott** [comment]
Still an issue for some components.

**Comment by hoverduck** [comment]
@rachelmcr we can close this, since we're no longer using the devdocs page for the visdiffs, correct?

I'm closing it, please re-open if I'm wrong :smile:
