### ISSUE TITLE
Add Vagrant/Docker wrapper to run tests in "headless" mode

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#390]
This is an enhancement suggested by @bisko - Add a wrapper to run the tests inside a Vagrant/Docker instance so they essentially run headlessly.  VNC can be used to observe them when necessary.

It's pretty much exactly what's being done via CircleCI, but this would be for running locally.

**Comment by alisterscott** [comment]
There looks like some official docker images from the Selenium project that we could use: https://github.com/SeleniumHQ/docker-selenium

I was thinking we could spin up a wp-calypso branch in docker and then use a separate docker to run tests against it

**Comment by lancewillett** [comment]
Project note: @hoverduck is taking a look at this now.
