### ISSUE TITLE
Add test to signup spec for e-mail verification

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#426]
1) Signup for a new account (likely just append this to an existing signup test, like for the Free account)
2) Compose a new post
3) Verify the user can't publish, and sees a prompt to verify their e-mail
4) Verify the e-mail
5) Publish the post

**Comment by alisterscott** [comment]
Was the regression that triggered this purely visual? Would an e2e find the problem?

**Comment by bsessions85** [comment]
Added in PR #671
