### ISSUE TITLE
Update report consolidation to collect results from all nodes

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#43]
The CircleCI tests are now executing in parallel, but it looks like the first node is the only one running the post job to run the reports through junit-viewer to put them in the pretty HTML output.  It may be as simple as just setting the `parallel: true` flag on the post command in circle.yml, but it may also be worth a wrapper script to SSH between the nodes to collect all the reports in one place.

**Comment by hoverduck** [comment]
Maybe worth closing if/when we move away from CircleCI.  Leaving open for now.

**Comment by alisterscott** [comment]
@hoverduck is this still an issue as far as you're aware?

**Comment by hoverduck** [comment]
No, when we went to CircleCI 2.0 I stopped running the junit-viewer for pretty-printing the results in a report.
