### ISSUE TITLE
Run Canaries in parallel

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#461]
Suggested by @gziolo 

> to make them faster, it takes 2:19 to execute `./run.sh`
> on the other hand it would be still around 2:45 instead of 3:55 with 2 containers

**Comment by gziolo** [comment]
We do that for Calypso unit tests. See example line in `circle.yml` file:
https://github.com/Automattic/wp-calypso/blob/master/circle.yml#L26

We pass container index and total number of container to the Mocha runner. It makes sure we run only subset of tests on each container. Related code:
https://github.com/Automattic/wp-calypso/blob/master/test/runner.js#L126

**Comment by hoverduck** [comment]
Fixed on the canary repo via https://github.com/Automattic/wp-e2e-tests-canary/pull/4
