### ISSUE TITLE
Look at using Yarn

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#462]
Suggested by @gziolo 

Look at using yarn over npm for dependencies to speed these up on  Circle.

CircleCI docs: https://circleci.com/docs/1.0/yarn/

**Comment by gziolo** [comment]
If you opt in for `yarn` I recommend updating `package.json` and freezing all dependencies to one version. `^6.3.19` - this is nice for development but invalidates cache quite often.

> CircleCI docs: https://circleci.com/docs/1.0/yarn/

They finally have proper way of using `yarn`. It wasn't the case a few weeks back :)

**Comment by hoverduck** [comment]
@alisterscott and I tried using Yarn and didn't see any immediate performance boost.  It may be worth re-evaluating in the future, but for now there doesn't seem to be enough of a difference to be worth the switch.
