### ISSUE TITLE
A secure way to store common credentials

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#467]
Encrypt in git? Or another way? How does this work with CircleCI

**Comment by hoverduck** [comment]
Detail from @brbrr in #896 

Maintaining config files for all our test targets is quite complicated, and often leads to compile errors (which isn't straightforward in CirleCI)

We can take similar approach mobile/desktop repo uses - encrypt config file and store it publically

Internal ref: PCYsg-3M8-p2
