### ISSUE TITLE
Catch OAuth2 error on domain search and retry

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#480]
This error is still occurring occasionally on domain search, and we can't seem to reproduce it reliably enough to figure out the cause and get a real fix in place.  So we should add something to the tests to detect this error and retry however a real user would do it.  Or at a minimum add tracking for when it happens so we can provide feedback to Calypso on the frequency of the issue

![image](https://cloud.githubusercontent.com/assets/7233112/24762848/96af3ab4-1abd-11e7-91f6-469455678ae8.png)

https://github.com/Automattic/wp-calypso/issues/3314

**Comment by alisterscott** [comment]
Haven't seen this for a long time actually, I believe changed domain providers so closing this down
