### ISSUE TITLE
Work out way for WooCommerce branches to run against wpcalypso

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#490]
I am using the `run-wrapper.sh` to change the target when working on a WooCommerce branch, but in CircleCI these must run against https://wpcalypso.wordpress.com

Is there a way to override this per branch? I don't wish to override it when working locally as I may be using calypso.localhost:3000 instead of wpcalypso.

**Comment by alisterscott** [comment]
@hoverduck do you know if this is possible?

**Comment by hoverduck** [comment]
With https://github.com/Automattic/wp-e2e-tests/pull/491 I added a command line option to run.sh to override the `calypsoBaseURL` config (something I've thought about before as a good idea, so this was a nice chance to add it).

Beyond that I'm not sure exactly what scenario you're looking for, so I'll leave the rest up to you.  If you're just trying to differentiate between runs locally and on CircleCI you can add a check for the `$CI` variable and apply the `-u http://calypso.localhost:3000` option if it's missing (or vice versa, add it to point to wpcalypso if it's set to true).

Another option I've thought about exploring for differentiating test runs is using more config files with some of [these options](https://github.com/lorenwest/node-config/wiki/Configuration-Files#file-load-order).  We could set the `$NODE_APP_INSTANCE` variable to something unique on each wrapper repo (for example) and use that to pick up different base configs.

**Comment by alisterscott** [comment]
Awesome @hoverduck, this is exactly what I need.
I just [updated](https://github.com/Automattic/wp-e2e-tests/pull/493) run-wrapper to pass this in and it all works 👍
