### ISSUE TITLE
Project Idea: schedule i18n screenshots once a week

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#494]
The i18n screenshots were created as a once-off thing to generate a bunch of files that are manually reviewed.

These are out of date now, but what if we got them up to date and then ran say regularly, say once a week, and had it so they fully automated the process of uploading them as a gallery to a site (using WordPress.com REST API?) so that we could historically see the changes and easily send them out for review by translators.

This would be a good meetup project or GM team activity.

**Comment by alisterscott** [comment]
@deBhal I've put this here to keep track of it

**Comment by deBhal** [comment]
This is a great idea! The screenshots were really useful, and we found a bunch of problems going through them.

That said, we (i18n) also need to figure out how to consume them. I think we should have a plan to avoid having them sit there collecting virtual dust before we implement this.

Maybe we could include them in the happiness i18n rotations.

**Comment by lancewillett** [comment]
Closing as this project is complete — thanks for driving this one @rachelmcr. 🎉
