### ISSUE TITLE
Page Editor spec frequently failing on CI

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#503]
I haven't been able to reproduce this locally at all, but the page editor spec has been failing extremely frequently on CircleCI the last week or so.  The screenshots often show a blank white page, or else what appears to be a fully loaded page with an error saying it timed out waiting for a selector.  As far as I can tell it's always on the publish verification step.

It happens occasionally on Posts, but Pages is ridiculous.  It also seems to be more common on my branch where I'm running multiple tests concurrently, so maybe it's a resource contention issue?  Or maybe it's a problem on CircleCI 2.0 but not 1.0?  Maybe we need to raise the timeouts on the tests going forward?

Just something to keep an eye on.

**Comment by hoverduck** [comment]
I tried running the tests in serial and still saw the same problem, so it's not a concurrency issue - https://circleci.com/gh/Automattic/wp-e2e-tests/8778

**Comment by hoverduck** [comment]
I _think_ that running `ensureSaved` before opening the preview solved the problem, although I still saw something similar on one run later (but the auto-retry worked fine).  So I'll leave this open for a little while to track it, but hopefully it's taken care of.

https://github.com/Automattic/wp-e2e-tests/commit/c6bf44736f4330ed882d2eb0573be355d5ec453d

**Comment by alisterscott** [comment]
Haven't seen this again, I think it would be the `ensureSaved()` call. Closing.
