### ISSUE TITLE
Try out Chrome Headless option

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#515]
Test it out to see if there are any performance benefits, especially on CI.

https://developers.google.com/web/updates/2017/04/headless-chrome

**Comment by hoverduck** [comment]
I tried to play around with this this afternoon and hit too many road blocks....the headless feature isn't quite ready for real usage with Selenium yet.  The latest version of ChromeDriver is 2.29, which _officially_ only supports Chrome v56-58, and the headless option isn't available until v59 (which is still in beta).  Things are moving fast, though, so I'll keep an eye on it and check back in a few weeks.

The problems I encountered:

1) The `driver.manage().window().setSize( )` function caused problems, making WebDriver complain `unknown error: cannot get automation extension`.  I stubbed out our `resizeWindow()` function entirely to get past it
2) The `sendKeys()` function isn't really supported, causing this error: `WebDriverError: unknown error: an X display is required for keycode conversions, consider using Xvfb`
To get around it I replaced the `element.sendKeys()` call with 

> driver.executeScript( `arguments[0].setAttribute("value", "${value}")`, element );

Alternatively it did work to just run the tests with Xvfb, but that kind of defeats the purpose of being headless.  Maybe it's still less resource intensive?

For posterity, I saved the changes I made in PR #533.

Reference: https://intoli.com/blog/running-selenium-with-headless-chrome/

**Comment by boldfacedesign** [comment]
@hoverduck thanks so much for the workaround for `sendKeys()` much appreciated.

**Comment by pumano** [comment]
Good news:
according to : https://bugs.chromium.org/p/chromedriver/issues/detail?id=1772 issue was fixed.

`The fix will be included in ChromeDriver 2.31. Its release date hasn't been determined yet.`

**Comment by yeshwanthvshenoy** [comment]
Just curious, but can a workaround using xvfb be done for the same? If yes how should it be run on a jenkins job to actually work properly. For an example, this is my jenkins job to run the tests.

```#!/usr/bin/env groovy
node {
  stage ('Checkout') {
    checkout scm
    echo "My branch is: ${env.BRANCH_NAME}"
  }
  
 
    stage ('TestExecution') {
      sh '''#!/bin/bash
	     pgrep -f webdriver-manager &> /dev/null
	     if [ "$?" -ne 1 ]; then
		   npm update protractor -g
                   webdriver-manager update
		   webdriver-manager start /dev/null 2>&1
		   sleep 1
	     fi
         protractor conf.js
         '''
    }
}
```

**Comment by hoverduck** [comment]
@yeshwanthvshenoy You should be able to just preface your shell command with `xvfb-run`

**Comment by brunogirin** [comment]
@hoverduck thanks for the workaround for `sendKeys()`! I've now tried with Chrome 60 and ChromeDriver 2.31 and it looks like `sendKeys()` works fine with those versions and the workaround is no longer needed.

For completeness, here is the full configuration that works for me:
- Ubuntu 16.04
- Selenium server 3.4.0
- Chrome 60
- ChromeDriver 2.31

**Comment by alisterscott** [comment]
@bsessions85 is trying this out in https://github.com/Automattic/wp-e2e-tests/pull/744

**Comment by bsessions85** [comment]
With the latest updates everything seems to work well.  HEADLESS=1 environment variable or -x flag on run.sh will use it in this repo.
