### ISSUE TITLE
Delete comment step in notifications spec not consistently deleting the comment

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-e2e-tests#535]
The notifications spec ends with a step to delete the comment that was just left on the test site: https://github.com/Automattic/wp-e2e-tests/blob/master/specs/wp-notifications-spec.js#L98

However, even though that test is passing, the comments aren't being deleted. The test site has pending comments from this test — currently, the oldest pending comment is from 2017/03/16 at 10:02 pm.

I did a manual test, and I believe the issue is that the "Comment trashed" message appears on the notification before the delete request actually occurs. If you close the browser window immediately after deleting the comment, it isn't actually deleted. If you leave the browser window opens for a couple seconds, the comment is deleted as expected.

**Comment by alisterscott** [comment]
Thanks for investigating this.

> I did a manual test, and I believe the issue is that the "Comment trashed" message appears on the notification before the delete request actually occurs.

Do you think this is a wp-calypso issue? We can add a delay before closing the window to make sure the request happens during test runs.

**Comment by alisterscott** [comment]
> Do you think this is a wp-calypso issue?

On a closer look I think it's waiting for the UNDO option to be unavailable to actually call the service to delete the comment.

I made a change to do this in #538 but on a fresh post I am still seeing some comments not deleted, so maybe it still needs to wait a couple of seconds even after UNDO disappearing for the request to be fully sent. It's a tricky one.
