### ISSUE TITLE
Jetpack: Run tests on master branch after merge

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#609]
Update the Jetpack test config to run against the master branch of the https://github.com/Automattic/jetpack repo after each merge.

1) Reconfigure our existing test sites on Pressable/GoDaddy/Bluehost to run the master branch (either via Bleeding Edge in the beta plugin, or manually)
2) Add a webhook to the Jetpack repo to trigger the tests on merge

The question on step 1 there is whether the beta plugin will refresh the plugin fast enough after the merge, or if we need a "manual" step to pull the branch before initiating the tests.

cc: @lezama

**Comment by brbrr** [comment]
That seems already implemented and could be closed. @hoverduck  could you confirm that I don't miss something?

**Comment by lezama** [comment]
great, where we can see the output?

**Comment by brbrr** [comment]
@lezama https://circleci.com/gh/Automattic/jetpack

**Comment by lezama** [comment]
😃! do we get warnings somewhere? a slack channel or within the Jetpack repo?

**Comment by brbrr** [comment]
Yep, we using #e2e-jetpack-notif slack channel

Internal ref: p6fDka-uh-p2
