### ISSUE TITLE
Replace /wp-login.php with /log-in

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#632]
Since Calypso now supports native logging in, we don't need to use `/wp-login.php`, we can just visit `/log-in` on the baseurl which should work, or maybe just visit /log-in as the auth URL

Investigate and replace the usages of wp-login.php

**Comment by lancewillett** [comment]
Note: the plan is to eventually replace `log-in` with a canonical, simpler `login` (I think during testing and initial rollout it was impossible to have both).

**Comment by hoverduck** [comment]
Fixed in #660
