### ISSUE TITLE
Japanese font missing in i18n NUX screenshots on CI

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#645]
The font packages are installed in the Dockerfile, and everything looks fine when running locally.  But for some reason the Japanese font isn't being loaded right on CircleCI, resulting in screenshots like this:

![image](https://user-images.githubusercontent.com/7233112/28526897-ed9b7646-7056-11e7-8360-b29328a37f7e.png)

**Comment by hoverduck** [comment]
The correct font packages are installed in the Docker image used for the tests here on the main repo, but the wrapper repos are still using CircleCI 1.0 for simplicity, and were lacking those packages.  In https://github.com/Automattic/wp-e2e-tests-i18n/issues/4 I just added a step to the circle.yml file to install the same fonts.

**Comment by akirk** [comment]
@hoverduck The fonts are missing again, see p1512451529000062-slack-C03872RR0. Could you look into fixing it again? Thank you!
