### ISSUE TITLE
Delete dynamically created Jetpack sites after test failures

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#690]
The Jetpack CI tests are built using the CircleCI Workflows capability with three tasks:

1) Build - Create / connect the site
2) Test - Execute the e2e tests
3) Destroy - Disconnect / delete the site

It works great as long as the tests are successful, but if they fail the Destroy task is never started.  Workflows lacks a capability to run a task even on failure.

This issue is to track the problem and manage the site deletion steps elsewhere, but keep in mind that the Test task is run on desktop/mobile in parallel, so we can't delete the site until both pieces are done.

**Comment by brbrr** [comment]
I've done some investigation on this:

- CircleCI does not support any sort of setup/teardown flows. 
- Magellan does have global [teardown](https://github.com/TestArmada/magellan#setup-and-teardown) support, with which we could solve this issue. 

I'll move forward and try this out

**Comment by brbrr** [comment]
This should be fixed in #911

**Comment by alisterscott** [comment]
@brbrr Can we close this now?

**Comment by brbrr** [comment]
With pleasure :)
