### ISSUE TITLE
Create a framework for notifying warnings to Slack etc

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#72]
At the moment when we come across an error that is kinda expected, like customizer failed to load, we use a bunch of code to notify slack as a warning then retry and continue. 

It would be nice to wrap this into a method on a helper class so there's only one line to call which does this for us.

**Comment by hoverduck** [comment]
Good idea.  One thing I'd like to add here is that every message to Slack should have the CircleCI build number (and maybe screensize?) so we can distinguish where the messages are coming from, which will be especially important once the tests are running against different baselines via live branches.

**Comment by alisterscott** [comment]
Mostly covered in #101
