### ISSUE TITLE
Investigate timeouts with chrome --headless option

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#754]
I tried updating the tests running on the Jetpack repo were updated with https://github.com/Automattic/jetpack/pull/8049 to use the `--headless` option after we merged #744 on wp-e2e-tests, but for some reason the tests were completely imploding with random failures - https://circleci.com/gh/Automattic/jetpack/1077

I switched back to forcing `xvfb-run` instead of the `-x` option on run.sh, and the tests ran cleanly.  We need to figure out what's different about the Jetpack test environment that's causing such havoc.

**Comment by hoverduck** [comment]
Seems like this was affecting the wpcom tests as well, not just Jetpack.  Although it only started happening here in the last hour or two...so it could still be something unrelated.

**Comment by alisterscott** [comment]
We haven't actually seen this for some time now - closing
