### ISSUE TITLE
Add e2e tests to the `/domains` flow

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-e2e-tests#759]
https://github.com/Automattic/wp-calypso/pull/18557 broke the `/domains` flow today - it was not until @hewsut reported (p1509110055000391-slack-domains-dev) it that we noticed the regression and @aidvu fixed it in https://github.com/Automattic/wp-calypso/pull/19226.

We plead thee e2e gods to shine upon this flow with your evertesting light 🙇

The simplest flow (similar to the regular domain purchase flow, you just don't pick the domain, themes... anything):
* Go to https://wordpress.com/start/domain-first/site-or-domain?new=random-domain.blog
* Click `Just buy a domain`.
* You are redirected to checkout with the domain in cart (note, however, that it's `https://wordpress.com/checkout/no-site` - meaning, at this point, it's not tied to any site - not sure if it changes anything for you, but wanted to point it out in case it does).

**Comment by alisterscott** [comment]
Completed in #763
