### ISSUE TITLE
Update domain purchase specs to use test domain registrar

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#760]
While discussing #759 with the domains-dev team I mentioned that we've always had a problem with our signup/domains tests that we can't purchase a domain because we don't want to alert ICANN with a bunch of registrations/cancellations.  But they informed me that we actually have a system in place to send registrations to a test environment with Tucows which will avoid all that hassle!

All we need to do is set the store sandbox cookie like we're already doing, and then purchase a `.live` domain.

This issue should drive an update to our NUX / Plan Purchase / Manage Domains specs to complete the flow.

**Comment by alisterscott** [comment]
I've tried this in https://github.com/Automattic/wp-e2e-tests/pull/763

**Comment by alisterscott** [comment]
Completed in #763
