### ISSUE TITLE
Cancel existing wpcalypso canary tests when starting a new one

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#765]
If multiple developers merge code into wp-calypso/master in quick succession, we'll end up with several canary runs against wpcalypso.wordpress.com.  Because the tests are initiated via API, we can't use CircleCI's built in auto-cancel function.  So we need to build some logic into the script that calls the API to see if there are any existing runs and then cancel them.

Offhand I'm not sure where in the chain that logic should go.

**Comment by alisterscott** [comment]
Do canaries on PRs eliminate the need to run them against wpcalypso on merge?

**Comment by hoverduck** [comment]
I've been thinking about that, and I'm not sure.  At least the wpcalypso canaries run on _every_ merge, so they'll catch PRs that never have the `Needs Review` label applied.  My original thought was that we should let the PR canaries run for a while before we look at turning these off, but maybe we're at that point now?  I haven't seen any real issues with them.

Another approach would be to turn the wpcalypso canaries into something slightly different.  Is there another set of tests we could run at this stage before deploying to production?  I'm not committed to that idea, it was just a thought.

**Comment by alisterscott** [comment]
I think we need to run every canary on wpcalypso since these are used for Slack messages when the canaries pass.

Looking at the run history for the canaries on wpcalypso I don't think running these on top of each other is even an issue anymore - so closing

https://circleci.com/build-insights/gh/Automattic/wp-e2e-tests-canary/master
