### ISSUE TITLE
Add tests for Customizer updates in WP 4.9

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#787]
WordPress 4.9 brings some updates to the customizer that it would be nice to cover in our flows.  For starters there's the ability to save a draft of your changes and preview them via custom URL.

There have also been some changes to the nav menus - https://make.wordpress.org/core/2017/11/07/nav-menu-improvements-in-the-customizer-in-4-9/

Others?

**Comment by brandonpayton** [comment]
Here is another change that added publishing options for Customizer changesets:
https://make.wordpress.org/core/2017/11/03/new-features-and-enhancements-with-customizer-changesets-in-4-9/

A Settings button was added to the Publish button and opens a view that allows you to save a changeset as a draft or schedule it to be published in the future.

**Comment by alisterscott** [comment]
Our forward focus for the e2e tests is on Calypso so we won't duplicate testing core WordPress customizer functionality like saving drafts of changes within our e2e tests - closing.
