### ISSUE TITLE
Add test for SSR themes page

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#795]
The server side rendered wordpress.com/themes page recently broke with upgrade to React 16

Can we add an e2e test that would capture this breakage of SSR pages? A logged out test?

**Comment by alisterscott** [comment]
@rachelmcr I believe you've done this as a signup test? Can I close this?

**Comment by rachelmcr** [comment]
Yes, we can close this. @brbrr added the test (`Sign up while purchasing premium theme`) in the signup spec so we have that page covered.
