### ISSUE TITLE
Create jurassic.ninja sites in advance to reduce total test execution time

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-e2e-tests#797]
Since we're planning to use the `jurassic.ninja` service to create fresh Jetpack sites for testing, it's worth to think about some optimization of the total test execution time. Currently, creating one of those sites takes around 30 secs.

It would be nice if we create and maintain a list of ready-to-use fresh `jurassic.ninja` sites (for example 20 of them). So every time a test needs a new Jetpack site, it pulls the oldest one from the list, removes it from the list, and initiates the creation of a new one.

This could help us reduce a large portion of the execution time for running Jetpack-related e2e tests.

cc @oskosk @seear @sirreal

**Comment by sirreal** [comment]
Sounds like a good idea, maybe we should open an issue right on the repo for discussion: https://github.com/oskosk/jurassic.ninja

**Comment by tyxla** [comment]
Good call, I've opened https://github.com/oskosk/jurassic.ninja/issues/55 and https://github.com/oskosk/jurassic.ninja/issues/56

**Comment by sirreal** [comment]
This is a good idea, but JN has gotten much faster recently, and there are issues are on the appropriate repo.
