### ISSUE TITLE
Jetpack Connect: Only disconnect inactive sites

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#811]
I've seen a fair number of failures in the Jetpack Connect test in the step that disconnects all of the existing sites.  Sometimes it gets stuck in a loop trying to remove the same site over and over, and sometimes there are just so many sites stuck out there that it times out while stepping through them all.  A few times I've run the mass-disconnect script from my sandbox to help clean things up.

How about this for a new approach: First, add an `after()` clause to each Connect test that disconnects the site that was just used.  Second, to clean up any stragglers that still remain - rather than delete _every_ connection before the connect test begins (which can easily step on other concurrent test runs), how about we use the red `(!)` icon in the sites list to only disconnect the ones that are inactive?  We could also just allow the above-mentioned `after()` clause handle things by itself, and add a cron that runs the disconnect script on the backend to clean up any stragglers once a day or so.

@seear - I think you were the one who initially put this together, do you see any issues with that approach?

I don't have time to implement this today, but I can handle it on Monday.

**Comment by seear** [comment]
> how about we use the red (!) icon in the sites list to only disconnect the ones that are inactive?

Merged in #809, along with the removal of the disconnects that were part of the test.

I didn't think there was a great deal of harm in leaving the sites connected until they expire, but the `after()` to disconnect after the test seems like a good idea. We could use the site url from the test to hit the settings url directly instead of futzing with the site switcher.

**Comment by hoverduck** [comment]
Ha...looks like I was just a little behind the times on that one.

**Comment by brbrr** [comment]
That's seems already the case, so we can close this issue, right? 
cc @hoverduck @seear

**Comment by seear** [comment]
> That's seems already the case, so we can close this issue, right?

Yep, done 👍
