### ISSUE TITLE
Update signup spec for email verification changes

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-e2e-tests#819]
The timing for new account verification emails is currently being tested (ref: p91bmw-da-p2), which broke the signup tests that relied on it (see #817).

Once the timing for those emails is finalized, we should update the signup spec accordingly:

- Reenable the check in `Sign up for a free site and log in via a magic link` for the number of expected emails to a new user.
- Possibly add a new test for new users that verifies the account email and publishes a post, taking into account the new timing for the verification email.

**Comment by alisterscott** [comment]
Fix in #1433
