### ISSUE TITLE
Update post editor spec due to masterbar removal

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-e2e-tests#820]
The masterbar was removed from the editor in https://github.com/Automattic/wp-calypso/pull/20174.

Currently the `Edit a Post` test in the post editor spec is failing because it tries to navigate to the posts list via the masterbar. We'll need to update the test to use a different approach now that the masterbar is gone.

**Comment by alisterscott** [comment]
Automattic/wp-calypso#20174 was reverted, but I've implemented a backwards compatible fix in #821
