### ISSUE TITLE
Remove support non-https sites

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#856]
We currently have some conditional code in our e2e tests for running against non HTTPS sites

We no longer un against GoDaddy or Bluehost so we should be able to remove this conditional code

An example: 

```
if ( httpsHost ) {
  postEditorToolbarComponent.publishThePost( { useConfirmStep: true } );
} else {
  postEditorToolbarComponent.publishAndPreviewPublished( { useConfirmStep: true } );
}
```

**Comment by alisterscott** [comment]
@hoverduck do you think this is okay to do? (I am happy to complete this task)

**Comment by brbrr** [comment]
If we planning to switch to jurassic.ninja - then it might be needed, since they are HTTP(until SSL cert is created which take few hours)

**Comment by alisterscott** [comment]
@brbrr thanks, that's good to know - I don't think we should do this in that case

**Comment by hoverduck** [comment]
With #951 I think that all of the hosts we're testing against are now https-enabled, so this may be safe to do now.

**Comment by alisterscott** [comment]
I'll create a PR for this
