### ISSUE TITLE
Update calypso.live handling to work with dserve

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#870]
The new dserve system is being stood up as a replacement for calypso.live.  In general it will be just a drop-in replacement, but there area couple of little things we should do to take advantage of it:

1) The only test that outright fails against the new system is the NUX test starting with a premium theme purchase...simply because it starts at `${calypsoBaseURL}/themes`, which doesn't specify a branch/hash.  It just needs to look for the config settings and add the query param if necessary.

1) The new system adds the ability to run with the query param `hash=.....` instead of just `branch=...`, so we should add that ability in the tests as well.  This support will be critical for taking full advantage of dserve to run tests against branches prior to merge.

This is all contingent on the DNS entry for calypso.live being updated to point to dserve.  There are other issues that aren't really worth fixing if you want to run before that happens (or you can workaround them by updating your local hosts file to point calypso.live to the dserve IP address).

**Comment by alisterscott** [comment]
This is now live and all working :)
