### ISSUE TITLE
Review Applitools usage in different targets

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-e2e-tests#891]
Right now Applitools `eyes` object is used in suites under `specs` folder, which means it is used in all targets(canary, full-suite, jetpack, woo(?))

That's redundant and may pollute visdiff reports and/or exceed our plan's screenshots limits. 

> The only limitation that I know of is the number of screenshots we send to Applitools, so unless we’re actually sending screenshots it shouldn’t affect our plan usage.

**Comment by rachelmcr** [comment]
This shouldn't be an issue for regular test runs. We only send screenshots if the `VISDIFF` env var is set, per the [eyes helper](https://github.com/Automattic/wp-e2e-tests/blob/1a7ba5c63775c1b7b4d50fd9520a14e628477181/lib/eyes-helper.js#L66). This setup will allow us to add visdiff tests to any of our test specs but only actually use Applitools/take screenshots when we intend to.
