### ISSUE TITLE
Use single NODE_CONFIG for all test targets

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-e2e-tests#896]
Maintaining config files for all our test targets is quite complicated, and often leads to compile errors (which isn't straightforward in CirleCI)

We can take similar approach mobile/desktop repo uses - encrypt config file and store it publically

Internal ref: PCYsg-3M8-p2

**Comment by hoverduck** [comment]
I forgot we already had an issue open on this - closing to #467
