### ISSUE TITLE
Create Style Guide for our e2e test framework

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-e2e-tests#923]
Together with a code style, we can use some kind of high-level style guide for our components/tests.

The most notable thing which differs the most - is the way we define element locators. There are other things that might be standardized. 

This ticket is mostly the place to discuss what things we can standardize.

**Comment by brbrr** [comment]
- Passing arrow functions (“lambdas”) to Mocha is discouraged. Lambdas lexically bind this and cannot access the Mocha context. https://mochajs.org/#arrow-functions

**Comment by alisterscott** [comment]
We now have a style guide, at least a start, feel free to add to it via PRs and examples 👍 

docs/style-guide.md
