### ISSUE TITLE
Add test step to verify pending invite

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#940]
https://github.com/Automattic/wp-calypso/pull/22395 added a new tab to the People page which allows you to view pending Invites from within Calypso.  That PR only enabled it on Staging, but it will be turned on for Production hopefully within a week.

Nothing should break with our existing tests, but it should be a simple matter to add a step after sending an invite to switch over to the Invites tab and verify that it shows up.  We could also add another test to check out the Revoke Invite functionality

**Comment by sofiavistas** [comment]
hey @hoverduck I have opened a quick PR to add a step for the pending invites :) https://github.com/Automattic/wp-e2e-tests/pull/1134

**Comment by alisterscott** [comment]
We have coverage on this now - closing
