### ISSUE TITLE
Investigate instability in 2fa login tests

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#995]
We've been getting a lot of failures on the 2fa login tests recently, so this issue is to drive an investigation and figure out what we can do to make them better.

Here are a couple of the error messages I've seen crop up:
`Your session has expired, please go back to the login screen`
![2fa-session-expired](https://user-images.githubusercontent.com/7233112/36816721-a992e116-1cac-11e8-90c7-108c4428f4fd.png)

`You can only request a code via SMS once per minute. Please wait and try again.`
![2fa-sms-once-per-minute](https://user-images.githubusercontent.com/7233112/36816723-ab083f78-1cac-11e8-9368-219cfd4d952a.png)

The second one can particularly be an issue with the way we're running the tests and picking accounts at random.  The hope is that the randomness coupled with the auto-retry will be enough to mask/bypass the problem, but maybe that's not enough.

**Comment by alisterscott** [comment]
I think this would be likely to be caused by having multiple parallel runs and 'clashes' between accounts running.

Could we use some new account only signups to then add 2fa and test a log on with it?

cc @Tug

**Comment by alisterscott** [comment]
One other thing I thought of is these specs don't have `@parallel` tags on each one so if one fails the whole lot gets re-run which could cause potential clashes.

We should investigate if we can add `@parallel` tags to them to stop multiple re-runs happening

**Comment by hoverduck** [comment]
> We should investigate if we can add @parallel tags to them to stop multiple re-runs happening

I gave this a try briefly earlier today and it seemed to work fine, but I was side-tracked by other things before I could push a PR.  I had a question for @rachelmcr whether moving the `@visdiff` tag lower in the hierarchy would cause problems, though.

**Comment by rachelmcr** [comment]
>I had a question for @rachelmcr whether moving the @visdiff tag lower in the hierarchy would cause problems, though.

Shouldn't be a problem. The only visdiff screenshots in this spec are in the first `Logging In and Out:` test, so that should be the only one needing a `@visdiff` tag. Moving the before and after hooks for `eyesHelper` into that test should be all that's needed.

**Comment by JavonDavis** [comment]
Updated these tests in https://github.com/Automattic/wp-e2e-tests/pull/1407 to only run on a specific label.
